name: Whoami
description: Logs the current Screenly user and team.

inputs:
  screenly_api_token:
    description: Screenly API token
    required: true
  api_base_url:
    description: Screenly API base URL
    required: false
    default: https://api.screenlyapp.com

runs:
  using: composite
  steps:
    - name: Screenly API whoami
      shell: bash
      run: |
        set -euo pipefail
        current_user=$(
          curl -fsSL -H "Authorization: Token ${{ inputs.screenly_api_token }}" \
            "${{ inputs.api_base_url }}/api/v4.1/users" \
            | jq -r '.[0] | "\(.first_name) \(.last_name) <\(.email)>"'
        )
        echo "Current user: ${current_user}"
        current_team=$(
          curl -fsSL -H "Authorization: Token ${{ inputs.screenly_api_token }}" \
            "${{ inputs.api_base_url }}/api/v4.1/teams" \
            | jq -r '.[] | select(.is_current == true)
                    | "\(.name) (\(.domain))"'
        )
        echo "Current team: ${current_team}"
