---
name: Update Edge App

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - main
      # Use master instead of main if that is your default branch.

run-name: Updating Edge App in ${{ github.event_name == 'workflow_dispatch' && 'stage' || (github.ref == 'refs/heads/main' && 'production' || 'stage') }}

jobs:
  deploy-stage:
    name: Updating Edge App in stage
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/development') || github.event_name == 'workflow_dispatch'
    environment: stage
    steps:
      - uses: actions/checkout@v7
      - uses: Screenly/edge-apps-actions/update@v26.9.1
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          environment: stage
          delete_missing_settings: 'true'
          edge_app_id: ${{ vars.STAGE_EDGE_APP_ID }}

  deploy-production:
    name: Updating Edge App in production
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # If your default branch is master, use: github.ref == 'refs/heads/master'
    environment: production
    steps:
      - uses: actions/checkout@v7
      - uses: Screenly/edge-apps-actions/update@v26.9.1
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          environment: production
          delete_missing_settings: 'true'
          edge_app_id: ${{ vars.PRODUCTION_EDGE_APP_ID }}
